branches:
  only:
  - master
  - "/^v.*$/"
language: cpp
matrix:
  include:
  - name: Linux x86_64
    dist: bionic
    script:
    - make -f Makefile.libretro -j 4
    - zip picodrive-Linux-x86_64.zip picodrive_libretro.so
  - name: Linux arm64
    dist: bionic
    arch: arm64
    before_install:
    - sudo apt-get install zip
    script:
    - make -f Makefile.libretro -j 4
    - zip picodrive-Linux-arm64.zip picodrive_libretro.so
  - name: Linux armv7 neon
    dist: bionic
    services:
    - docker
    before_install:
    - sudo apt-get install zip
    script:
    - docker pull dockcross/linux-armv7
    - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-armv7
      make -f Makefile.libretro platform=unix-armv-neon-hardfloat -j 4
    - zip picodrive-Linux-arm.zip picodrive_libretro.so
  - name: OSX x86_64
    os: osx
    osx_image: xcode11.2
    script:
    - make -f Makefile.libretro -j 4
    - zip picodrive-OSX-x86_64.zip picodrive_libretro.dylib
  - name: Windows x86_64
    os: windows
    before_install:
    - choco install make --ignore-checksums
    script:
    - make -f Makefile.libretro platform=win -j 4
    - 7z a picodrive-Windows-x86_64.zip picodrive_libretro.dll
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VYzM2Usm42Kv74HFJ7YeWhsNx7zq/br7biCdj6mghrtXFYxH3wzBM/qexvQOB/oVX8rpo9ThRJHr4zCBFY5+mhRZVGbCjatUfyRgTZbI3pgFxKFMiVAeat2BBr/s6nCiaErrWGON4xLMNAuqTq1Nie+HeoTBfGzFbu4WGJIuh1Sb6HkDmOr1m7oXr47OxL5RFzJKhBx0K2Vm9rMfnS1Nmsw4j1yUPsBPPYS0pLGv8X9BIYr5LOOPA2oAD8/WrF3r54Xxi/nI//xEui5OLl6V6qLqI9g82Tmb11HEiIt9Cqr5AuEzY583qQvx9OK2bw3S1o4Gj1sDP17EHh2cnMoR2Lf8g874bUmdPadf8SVxy+FUf9VwWp1GJA9gHWQIiTqKJO5i2beIbIKOSKojJ58Ph1WgM26Cj67NUp6kXWNtHgwU+YqwX5cSKhewcm+tQRPjsTe7cWuEnahp2bU7uPW4Opk0n7yXaxOLJ3oFZjBE4pr8LyCqVUeya60V2GO+TsiavLjUjhi/bu1MzVxAWRG1bYl0NoJQvBOwIFkCMXtoE64WQ/PyjvopM3Ntd44sdVeNN0SjfVkuKiJnB2IxlR8cgH7lp3R9FH/BbMekG5Xls1hZ3ysJQjVPFKe3GDIwAcHvPWhvRYqwhUgt0GTanyKyQhvRyPCxHeAc8p1UqnF5fbo=
  file:
  - picodrive-Linux-x86_64.zip
  - picodrive-Linux-arm64.zip
  - picodrive-Linux-arm.zip
  - picodrive-OSX-x86_64.zip
  - picodrive-Windows-x86_64.zip
  on:
    repo: piepacker/picodrive
    tags: true
